### ISSUE TITLE
Investigate high rate of replay upload timeouts

### ISSUE THREAD

**Issue by peppy** [ppy/osu-server-spectator#220]
![Image](https://github.com/ppy/osu-server-spectator/assets/20418176/2cfb985f-135f-4f16-9423-cc305fc912a7)

https://sentry.ppy.sh/organizations/ppy/issues/34904/

**Comment by peppy** [comment]
@bdach to follow up on this, we figured that the number being reported on datadog was much higher than actual, but I forget the reason why, or how i confirmed that this was the case. or if we actually decided this was still an issue..

```sql
root@db-master.osu.io:osu> select has_replay, count(*) from scores where preserve = 1 and passed = 1 and legacy_score_id is null and id between 2386002880 and 238700288
                        -> 0 group by has_replay;
+------------+----------+
| has_replay | count(*) |
+------------+----------+
| 1          | 22345    |
| 0          | 3669     |
+------------+----------+
```

**Comment by bdach** [comment]
That query is missing an `approved in (1, 2)`.

Running the query did look significantly better but we never got to explain why the numbers were being overestimated like that. I believe we did rule out aborted submission.

Next step would be to take a sample of those timeout messages from logs or from sentry and look for possible patterns in database. Or just blindly try increasing timeout I guess.

**Comment by peppy** [comment]
> That query is missing an `approved in (1, 2)`.

aha, that's the one.

```sql
root@db-master.osu.io:osu> select has_replay, count(*) from scores join osu_beatmaps using (beatmap_id) where preserve = 1 and passed = 1 and legacy_score_id is null an
                        -> d id between 2386002880 and 2387002880 and approved in (1,2) group by has_replay;
+------------+----------+
| has_replay | count(*) |
+------------+----------+
| 1          | 21148    |
| 0          | 36       |
+------------+----------+
```

**Comment by peppy** [comment]
Let's close this one for the time being. As we discovered, the failure rate is actually very low.

**Comment by bdach** [comment]
I'd still want to investigate the metrics themselves and why they're overreporting the actual count. Maybe we can save on some unnecessary work in the server.
