### ISSUE TITLE
Mod compatibility needs to be checked server-side

### ISSUE THREAD

**Issue by peppy** [ppy/osu-server-spectator#45]
Basically we need an implementation [similar to osu-web](https://github.com/ppy/osu-web/blob/05ca44bcb6f0b99b1a12f2923131599498aa65e1/app/Libraries/Multiplayer/Mod.php) to ensure correct mods are chosen by the client.

This is already enforced client side but we shouldn't be relying on that forever.

**Comment by bdach** [comment]
I'd probably be in favour of adding something like that game side, and then seeing if we can put it in place of the current incompatibility system (which we already wanted to do, because it redundantly requires specifications on both ends of the incompatibility).

**Comment by peppy** [comment]
Yep, that's the goal. Would be an API exposed by `osu.Game`.
