### ISSUE TITLE
Server concurrency limiting isn't enforced when no state is initialised for a user

### ISSUE THREAD

**Issue by peppy** [ppy/osu-server-spectator#47]
The current method of ensuring state consistency across (potentially) multiple connects and disconnects by the same user is to clean up any state which is owned by a previous user before allowing a new connection on the server.

This works fine.. until the same user connects twice to the server, not taking out a state either time. You now have a situation where there are two connections from the same user potentially sharing state data.

**Comment by bdach** [comment]
I believe https://github.com/ppy/osu-server-spectator/issues/80 should cover this, so closing.
